motore_1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: motore_1_joint
    joint_speed: 0.5
    motor:
        id: 1
        init: 0
        min: 0
        max: 4095

motore_2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: motore_2_joint
    joint_speed: 0.5
    motor:
        id: 2
        init: 0
        min: 4095
        max: 0

motore_3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: motore_3_joint
    joint_speed: 0.5
    motor:
        id: 3
        init: 0
        min: 4095
        max: 0

motore_4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: motore_4_joint
    joint_speed: 0.5
    motor:
        id: 4
        init: 0
        min: 0
        max: 4095
